example/config/routes.rb
Rails.application.routes.draw do
  resources :blogs, only: [:show], subdomainify: true do
    resources :articles, only: [:show]
  end

  root to: "blogs#index"
end

example/app/models/article.rb
class Article
  extend ActiveModel::Naming

  ARTICLES = [{ blog_slug: "foo", title: "Hello, world", slug: "hello-world" },
              { blog_slug: "foo", title: "Lorem",        slug: "lorem" },
              { blog_slug: "bar", title: "Example!",     slug: "example" }]

  attr_accessor :blog_slug, :title, :slug

  def self.find_by_blog_slug(slug)
    ARTICLES.select { |article| article[:blog_slug] == slug }.map do |article|
      Article.new(article)
    end
  end

  def self.find_by_slug(slug)
    Article.new(ARTICLES.find { |article| article[:slug] == slug })
  end

  def initialize(params)
    self.blog_slug = params[:blog_slug]
    self.title = params[:title]
    self.slug = params[:slug]
  end

  def to_param
    self.slug
  end
end

example/app/models/blog.rb
class Blog
  extend ActiveModel::Naming

  BLOGS = [{ name: "My Foo Blog",     slug: "foo", },
           { name: "My Awesome Blog", slug: "bar", }]

  attr_accessor :name, :slug

  def self.all
    BLOGS.map do |blog|
      Blog.new(blog)
    end
  end

  def self.find_by_slug(slug)
    Blog.new(BLOGS.find { |blog| blog[:slug] == slug })
  end

  def initialize(params)
    self.name = params[:name]
    self.slug = params[:slug]
  end

  def to_param
    self.slug
  end

  def articles
    Article.find_by_blog_slug(self.slug)
  end
end

example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

example/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find_by_slug(params[:id])
    @blog = Blog.find_by_slug(params[:blog_id])
  end

end

example/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find_by_slug(params[:id])
    @articles = @blog.articles
  end

end

example/app/helpers/application_helper.rb
module ApplicationHelper
end

example/app/views/articles/show.html.erb
<h2><%= link_to @blog.name, blog_path(@blog) %></h2>

<h3><%= @article.title %></h3>

<p>Unfortunately, we don't have any real content here. :'(</p>

example/app/views/blogs/index.html.erb
<ul>
<% @blogs.each do |blog| %>
  <li><%= link_to blog.name, blog_path(blog) %></li>
<% end %>
</ul>

example/app/views/blogs/show.html.erb
<h2><%= link_to @blog.name, blog_path(@blog) %></h2>

<ul>
<% @articles.each do |article| %>
  <li><%= link_to article.title, blog_article_path(@blog, article) %></li>
<% end %>
</ul>

example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
</head>
<body>

<h1><%= link_to "Example", root_path %></h1>

<hr>

<%= yield %>

<hr>

<em>Note, you may have to use <%= link_to "lvh.me", root_url(domain: "lvh.me") %> for this example to work.</em>

<pre>
params: <%= params.inspect %>
path: <%= request.fullpath %>
</pre>

</body>
</html>